apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: lovme-feriekalkulator
  namespace: medlemskap
  labels:
    team: medlemskap
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: /isalive
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 3000
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  ingresses:
    - https://lovme-feriekalkulator.intern.dev.nav.no
