name: Build & test PR

on:
  pull_request:

jobs:
  build-test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # ratchet:step-security/harden-runner@v2.19.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # ratchet:pnpm/action-setup@v6.0.3

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # ratchet:actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          pnpm config set @navikt:registry https://npm.pkg.github.com
          pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Run tests
        run: pnpm test --runInBand

      - name: Build
        run: pnpm build
