name: Deploy to mock-ekstern
run-name: Deploy '${{ github.ref_name }}' to 'mock'

on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build:
    name: Build and deploy to NAIS
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
      - name: Set up pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # ratchet:pnpm/action-setup@v6.0.4
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6.4.0
        with:
          node-version: "24.x"
          cache: "pnpm"
      - name: Install dependencies
        run: |
          pnpm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          pnpm config set @navikt:registry https://npm.pkg.github.com
          pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run tests
        run: pnpm test --runInBand
      - name: Build
        run: pnpm build
      - uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: medlemskap
          dockerfile: Dockerfile
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - uses: nais/deploy/actions/deploy@823ec9b7e305ce7cf911d0f9a25f7da9d7486cf2 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais.yaml
          VAR: image=${{ steps.docker-push.outputs.image }}
